In [8]:
import numpy as np

def search_and_prune(MyOD, start_node):
    MyOD = np.array(MyOD)  # 转换为 numpy 数组
    total_node_cango = [start_node]  # 初始化为目标节点
    visited_nodes = set()  # 已访问的节点集合
    flag = 0  # 记录迭代次数
    depth_nodes = []  # 存储每轮迭代的深度节点

    while total_node_cango:  # 当还有可搜索的节点时
        print(f"\nIteration {flag + 1}: Start nodes {total_node_cango}")
        
        new_nodes = []
        
        for target in total_node_cango:
            # 找到所有能到达目标节点的节点
            nodes_reaching_target = [i for i in range(len(MyOD)) if MyOD[i][target] == 1]
            new_nodes.extend(nodes_reaching_target)

        # 去重，排除已访问过的节点
        new_nodes = list(set(new_nodes) - visited_nodes)

        # 如果没有新节点加入，退出循环
        if not new_nodes:
            break

        # 记录已访问的节点
        visited_nodes.update(new_nodes)
        
        # 删除没有新出边或入边的节点
        all_possible_nodes = set(range(len(MyOD)))
        connected_nodes = set(new_nodes) | set(total_node_cango)
        nodes_to_remove = all_possible_nodes - connected_nodes
        
        for node in nodes_to_remove:
            MyOD[:, node] = 0  # 删除所有指向该节点的边
            MyOD[node, :] = 0  # 删除该节点指向其他节点的边

        # 更新为下一轮要探索的节点
        total_node_cango = new_nodes
        flag += 1
        
        # 存储当前深度的节点
        depth_nodes.append((flag, new_nodes))

        # 打印当前状态
        print(f"New nodes to explore: {total_node_cango}")
        print("Updated MyOD matrix:")
        print(MyOD)

    print("\nSearch complete.")
    
    # 打印最深的节点
    if depth_nodes:
        max_depth = max(depth_nodes, key=lambda x: x[0])  # 找到最大深度
        print(f"Most deep nodes at depth {max_depth[0]}: {max_depth[1]}")
    else:
        print("No nodes found.")


In [9]:
MyOD = [
    [0, 1, 0, 0],  # 节点 0 到节点 1
    [0, 0, 1, 0],  # 节点 1 到节点 2
    [0, 1, 0, 0],  # 节点 2 到节点 1
    [0, 0, 1, 0],  # 节点 3 到节点 2
]
start_node = 2  # 起始目标节点
search_and_prune(MyOD, start_node)



Iteration 1: Start nodes [2]
New nodes to explore: [1, 3]
Updated MyOD matrix:
[[0 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 1 0]]

Iteration 2: Start nodes [1, 3]
New nodes to explore: [2]
Updated MyOD matrix:
[[0 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 1 0]]

Iteration 3: Start nodes [2]

Search complete.
Most deep nodes at depth 2: [2]
